In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math

In [2]:
alfa = 0.25 # m²/s
deltat = 1e-2 # s
deltax = 0.1 # m
deltay = 0.1 # m
Lx = 0.5 # m
Ly = 0.5 # m
tmax = 15 # s

In [3]:
x = np.linspace(0, Lx, int(Lx/deltax))
y = np.linspace(0, Ly, int(Ly/deltay))
t = np.linspace(0, tmax, int(tmax/deltat))
int(Lx/deltax)

5

In [4]:
listatempo = []
for _ in range(tmax):
    matrix = np.zeros((len(y),len(x)))
    listatempo.append(matrix)

In [5]:
for m,matrix in enumerate(listatempo):
    for i,linha in enumerate(matrix):
        for j,elem in enumerate(linha):
            if(i == 0):
                listatempo[m][i][j] = 100
print(listatempo)

[array([[100., 100., 100., 100., 100.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.]]), array([[100., 100., 100., 100., 100.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.]]), array([[100., 100., 100., 100., 100.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.]]), array([[100., 100., 100., 100., 100.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.]]), array([[100., 100., 100., 100., 100.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.]]), array([[100., 

In [10]:

copia = listatempo.copy()
for m,matrix in enumerate(copia):
    for i,linha in enumerate(matrix):
        for j,elem in enumerate(linha):
            if(i != 0 and j != 0 and i != int(Lx/deltax)-1 and j != int(Ly/deltay)-1 and m != tmax-1):
                Tx = copia[m][i+1][j] - 2*copia[m][i][j] + copia[m][i-1][j]
                Ty = copia[m][i][j+1] - 2*copia[m][i][j] + copia[m][i][j-1]
                copia[m+1][i][j] = alfa*deltat*((Tx/(deltax**2))+(Ty/(deltay**2))) + copia[m][i][j]
for matrix in copia:
    print(matrix)

[[100. 100. 100. 100. 100.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
[[100. 100. 100. 100. 100.]
 [  0.  25.  25.  25.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
[[100.   100.   100.   100.   100.  ]
 [  0.    31.25  37.5   31.25   0.  ]
 [  0.     6.25   6.25   6.25   0.  ]
 [  0.     0.     0.     0.     0.  ]
 [  0.     0.     0.     0.     0.  ]]
[[100.     100.     100.     100.     100.    ]
 [  0.      35.9375  42.1875  35.9375   0.    ]
 [  0.       9.375   12.5      9.375    0.    ]
 [  0.       1.5625   1.5625   1.5625   0.    ]
 [  0.       0.       0.       0.       0.    ]]
[[100.       100.       100.       100.       100.      ]
 [  0.        37.890625  46.09375   37.890625   0.      ]
 [  0.        12.5       15.625     12.5        0.      ]
 [  0.         2.734375   3.90625    2.734375   0.      ]
 [  0.         0.         0.         0.         0.    

In [7]:
# listaplot = []
# listaplot.append(copia[0])
# for i, linha in enumerate(copia):
#     if(i%10==0):
#         listaplot.append(linha)
        
        
# for linha in listaplot:
#     plt.plot(x,linha, '-')
# plt.grid()
# plt.show()

In [14]:
round(copia[10][1][1], 2)

42.27

In [15]:
round(copia[1][1][1], 2)

25.0