In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math

In [2]:
alfa = 0.25 # m²/s
deltat = 1e-3 # s
deltax = 0.08 # m
deltay = 0.08 # m
Lx = 0.4 # m
Ly = 0.4 # m
tmax = 100 # s
f0 = alfa*deltat/(deltax**2)

In [3]:
x = np.linspace(0, Lx, int(Lx/deltax))
y = np.linspace(0, Ly, int(Ly/deltay))
t = np.linspace(0, tmax, int(tmax/deltat))
int(Lx/deltax)

5

In [36]:
listatempo = []
for i in range(tmax):
    matrix = np.zeros((len(y),len(x)))
    listatempo.append(matrix)

In [37]:
for m,matrix in enumerate(listatempo):
    for i,linha in enumerate(matrix):
        for j,elem in enumerate(linha):
            if(i == 0):
                listatempo[m][i][j] = 150
            if(j==len(x)-1):
                listatempo[m][i][j] = 50
print(listatempo)

[array([[150., 150., 150., 150.,  50.],
       [  0.,   0.,   0.,   0.,  50.],
       [  0.,   0.,   0.,   0.,  50.],
       [  0.,   0.,   0.,   0.,  50.],
       [  0.,   0.,   0.,   0.,  50.]]), array([[150., 150., 150., 150.,  50.],
       [  0.,   0.,   0.,   0.,  50.],
       [  0.,   0.,   0.,   0.,  50.],
       [  0.,   0.,   0.,   0.,  50.],
       [  0.,   0.,   0.,   0.,  50.]]), array([[150., 150., 150., 150.,  50.],
       [  0.,   0.,   0.,   0.,  50.],
       [  0.,   0.,   0.,   0.,  50.],
       [  0.,   0.,   0.,   0.,  50.],
       [  0.,   0.,   0.,   0.,  50.]]), array([[150., 150., 150., 150.,  50.],
       [  0.,   0.,   0.,   0.,  50.],
       [  0.,   0.,   0.,   0.,  50.],
       [  0.,   0.,   0.,   0.,  50.],
       [  0.,   0.,   0.,   0.,  50.]]), array([[150., 150., 150., 150.,  50.],
       [  0.,   0.,   0.,   0.,  50.],
       [  0.,   0.,   0.,   0.,  50.],
       [  0.,   0.,   0.,   0.,  50.],
       [  0.,   0.,   0.,   0.,  50.]]), array([[150., 

In [38]:

copia = listatempo.copy()
for m,matrix in enumerate(copia):
    for i,linha in enumerate(matrix):
        for j,elem in enumerate(linha):
            if(i != 0 and i != int(Lx/deltax)-1 and j != int(Ly/deltay)-1 and m != tmax-1):
                if(j != 0) :
                    Tx = copia[m][i+1][j] - 2*copia[m][i][j] + copia[m][i-1][j]
                    Ty = copia[m][i][j+1] - 2*copia[m][i][j] + copia[m][i][j-1]
                    copia[m+1][i][j] = alfa*deltat*((Tx/(deltax**2))+(Ty/(deltay**2))) + copia[m][i][j]
                elif(j==0):
                    copia[m+1][i][j]=f0*(2*copia[m][i+1][j]+copia[m][i][j+1]+copia[m][i][j-1])
for matrix in copia:
    print(matrix)

[[150. 150. 150. 150.  50.]
 [  0.   0.   0.   0.  50.]
 [  0.   0.   0.   0.  50.]
 [  0.   0.   0.   0.  50.]
 [  0.   0.   0.   0.  50.]]
[[150.       150.       150.       150.        50.      ]
 [  1.953125   5.859375   5.859375   7.8125    50.      ]
 [  1.953125   0.         0.         1.953125  50.      ]
 [  1.953125   0.         0.         1.953125  50.      ]
 [  0.         0.         0.         0.        50.      ]]
[[1.50000000e+02 1.50000000e+02 1.50000000e+02 1.50000000e+02
  5.00000000e+01]
 [2.33459473e+00 1.11083984e+01 1.13372803e+01 1.47094727e+01
  5.00000000e+01]
 [2.10571289e+00 3.05175781e-01 3.05175781e-01 3.98254395e+00
  5.00000000e+01]
 [1.95312500e+00 7.62939453e-02 7.62939453e-02 3.67736816e+00
  5.00000000e+01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  5.00000000e+01]]
[[150.         150.         150.         150.          50.        ]
 [  2.55155563  15.77806473  16.44563675  20.82204819  50.        ]
 [  2.11763382   0.78856945   0

In [22]:
# listaplot = []
# listaplot.append(copia[0])
# for i, linha in enumerate(copia):
#     if(i%10==0):
#         listaplot.append(linha)
        
        
# for linha in listaplot:
#     plt.plot(x,linha, '-')
# plt.grid()
# plt.show()

In [23]:
round(copia[10][1][1], 2)

37.57

In [9]:
round(copia[1][1][1], 2)

5.86